export const initialCurrentUser = {
  name: "Mr. Bello",
  role: "Guidance Counselor",
  dept: "Student Wellness",
  email: "t.bello@school.edu",
};

export const AUTHORITIES = [
  "Mr. Bello",
  "Mrs. Adeyemi",
  "Mr. Okafor",
  "Ms. Grant",
  "Unassigned",
];

export const initialReports = [
  {
    id: "SS-2026-0001",
    title: "Repeated food-taking and threats at lunch",
    category: "Bullying",
    desc: "A group of senior students have been taking my food at lunch and threatening me if I tell anyone. This has happened at least four times this term.",
    date: "2026-06-28",
    location: "Main dining hall",
    people: "A few senior boys, not sure of names",
    files: ["lunchroom_note.jpg"],
    anon: true,
    status: "Under Investigation",
    urgency: "High",
    assigned: "Mr. Bello",
    timeline: [
      { d: "2026-06-28", t: "Report submitted" },
      { d: "2026-06-29", t: "Assigned to Mr. Bello" },
      { d: "2026-07-01", t: "Marked as Under Investigation" },
    ],
    notes: [
      {
        a: "Mr. Bello",
        d: "2026-07-01",
        t: "Spoke with dining hall supervisor to increase presence during lunch.",
      },
    ],
    log: [
      { d: "2026-06-28", t: "Report created via anonymous form" },
      { d: "2026-06-29", t: "Status changed to Open" },
      { d: "2026-07-01", t: "Status changed to Under Investigation" },
    ],
  },
  {
    id: "SS-2026-0002",
    title: "Exposed wiring near west stairwell",
    category: "Safety Hazard",
    desc: "The wiring near the west dormitory stairwell is exposed and it sparked once during the rain last week. It looks dangerous especially at night.",
    date: "2026-07-02",
    location: "West dormitory stairwell",
    people: "",
    files: ["stairwell.jpg", "stairwell_2.jpg"],
    anon: true,
    status: "Open",
    urgency: "Urgent",
    assigned: "Unassigned",
    timeline: [{ d: "2026-07-02", t: "Report submitted" }],
    notes: [],
    log: [{ d: "2026-07-02", t: "Report created via anonymous form" }],
  },
  {
    id: "SS-2026-0003",
    title: "Anonymous notes left in locker",
    category: "Harassment",
    desc: "Someone keeps leaving notes in my locker that make me uncomfortable. I do not know who it is, but it has happened three times now.",
    date: "2026-06-19",
    location: "Locker room, Block C",
    people: "Unknown",
    files: [],
    anon: true,
    status: "Resolved",
    urgency: "Medium",
    assigned: "Mrs. Adeyemi",
    timeline: [
      { d: "2026-06-19", t: "Report submitted" },
      { d: "2026-06-20", t: "Assigned to Mrs. Adeyemi" },
      { d: "2026-06-24", t: "Locker relocated, monitoring installed" },
      { d: "2026-06-27", t: "Marked as Resolved" },
    ],
    notes: [
      {
        a: "Mrs. Adeyemi",
        d: "2026-06-24",
        t: "Relocated the student's locker to a monitored area as a precaution.",
      },
    ],
    log: [
      { d: "2026-06-19", t: "Report created via anonymous form" },
      { d: "2026-06-27", t: "Status changed to Resolved" },
    ],
  },
  {
    id: "SS-2026-0004",
    title: "Group chat exclusion and mockery",
    category: "Bullying",
    desc: "A classmate is being excluded and mocked in the class group chat by most of the class. Screenshots attached.",
    date: "2026-07-05",
    location: "Online / class group chat",
    people: "Multiple classmates",
    files: ["screenshot1.png", "screenshot2.png"],
    anon: false,
    status: "Open",
    urgency: "Medium",
    assigned: "Unassigned",
    timeline: [{ d: "2026-07-05", t: "Report submitted" }],
    notes: [],
    log: [
      { d: "2026-07-05", t: "Report created, reporter chose to be identified" },
    ],
  },
  {
    id: "SS-2026-0005",
    title: "Unsafe, unlit vending machine area",
    category: "Safety Hazard",
    desc: "Not sure who to tell this to, but the vending machine area feels unsafe after dark. There is no lighting at all back there.",
    date: "2026-06-22",
    location: "Rear courtyard",
    people: "",
    files: [],
    anon: true,
    status: "Resolved",
    urgency: "Low",
    assigned: "Mr. Okafor",
    timeline: [
      { d: "2026-06-22", t: "Report submitted" },
      { d: "2026-06-25", t: "Lighting installed" },
      { d: "2026-06-26", t: "Marked as Resolved" },
    ],
    notes: [],
    log: [{ d: "2026-06-22", t: "Report created via anonymous form" }],
  },
  {
    id: "SS-2026-0006",
    title: "Student showing signs of withdrawal and distress",
    category: "Mental Health Concern",
    desc: "A classmate has seemed really withdrawn lately, stopped eating lunch with friends, and mentioned feeling hopeless once. Worried about them.",
    date: "2026-07-06",
    location: "",
    people: "A classmate, prefer not to name",
    files: [],
    anon: true,
    status: "Under Investigation",
    urgency: "Urgent",
    assigned: "Mr. Bello",
    timeline: [
      { d: "2026-07-06", t: "Report submitted" },
      { d: "2026-07-06", t: "Escalated to Guidance Counselor immediately" },
    ],
    notes: [
      {
        a: "Mr. Bello",
        d: "2026-07-06",
        t: "Reached out to student for a wellness check via homeroom teacher.",
      },
    ],
    log: [
      { d: "2026-07-06", t: "Report created via anonymous form" },
      { d: "2026-07-06", t: "Urgency set to Urgent" },
    ],
  },
  {
    id: "SS-2026-0007",
    title: "Comments about accent and background",
    category: "Discrimination",
    desc: "Some students keep mocking my accent and where my family is from during group work. Teachers have not noticed.",
    date: "2026-07-03",
    location: "Classroom 4B",
    people: "A small group in 4B",
    files: [],
    anon: true,
    status: "Open",
    urgency: "Medium",
    assigned: "Unassigned",
    timeline: [{ d: "2026-07-03", t: "Report submitted" }],
    notes: [],
    log: [{ d: "2026-07-03", t: "Report created via anonymous form" }],
  },
  {
    id: "SS-2026-0008",
    title: "Shoving incident near bike racks",
    category: "Violence",
    desc: "Witnessed two students shoving each other near the bike racks after school, looked like it could have escalated.",
    date: "2026-06-30",
    location: "Bike racks, north entrance",
    people: "Two male students, unknown names",
    files: [],
    anon: true,
    status: "Resolved",
    urgency: "High",
    assigned: "Ms. Grant",
    timeline: [
      { d: "2026-06-30", t: "Report submitted" },
      { d: "2026-07-01", t: "Both students spoken to separately" },
      { d: "2026-07-02", t: "Marked as Resolved" },
    ],
    notes: [],
    log: [{ d: "2026-06-30", t: "Report created via anonymous form" }],
  },
];

export const initialNotifications = [
  {
    type: "new",
    text: 'New report submitted: "Exposed wiring near west stairwell"',
    time: "2 hours ago",
  },
  {
    type: "urgent",
    text: 'Urgent case flagged: "Student showing signs of withdrawal and distress"',
    time: "1 day ago",
  },
  {
    type: "assign",
    text: "Case SS-2026-0001 assigned to you",
    time: "2 days ago",
  },
  {
    type: "update",
    text: "Investigation update on SS-2026-0003",
    time: "4 days ago",
  },
  {
    type: "resolved",
    text: "Case SS-2026-0005 marked as Resolved",
    time: "6 days ago",
  },
];

export const staffUsers = [
  {
    name: "Mr. Bello",
    role: "Guidance Counselor",
    dept: "Student Wellness",
    email: "t.bello@school.edu",
  },
  {
    name: "Mrs. Adeyemi",
    role: "Principal",
    dept: "Administration",
    email: "f.adeyemi@school.edu",
  },
  {
    name: "Mr. Okafor",
    role: "Teacher",
    dept: "Facilities Liaison",
    email: "c.okafor@school.edu",
  },
  {
    name: "Ms. Grant",
    role: "Teacher",
    dept: "Discipline Committee",
    email: "l.grant@school.edu",
  },
];

export const CATEGORIES = [
  "Bullying",
  "Harassment",
  "Violence",
  "Discrimination",
  "Mental Health Concern",
  "Safety Hazard",
  "Other",
];
export const URGENCIES = ["Low", "Medium", "High", "Urgent"];
export const STATUSES = ["Open", "Under Investigation", "Resolved"];
